services:
  api:
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.timetable-api.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.timetable-api.entrypoints=https
      - traefik.http.services.timetable-api.loadbalancer.server.port=8000
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
